apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default-org
  description: The Default Organization
  links:
    - url: https://tanzu.vmware.com/support
      title: Tanzu Support Website
spec:
  type: organization
  profile:
    displayName: Nordics Organization
    email: nordics@tanzu.dk
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [denmark-team, sweeden-team, norway-team]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: nordics-group
  description: A Default Group Location
spec:
  targets:
    - ./teams.yaml
    - ./users.yaml
