apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tap-gui-domain
  description: Everything related to the Tanzu Application Platform GUI
  links:
    - url: http://example.com/domain/cloud-apps/
      title: Domain Readme
    - url: http://example.com/domains/cloud-apps/dashboard
      title: Cloud Apps Dashboard
      icon: dashboard
spec:
  owner: denmark-team
